/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my_first_plugin;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ExamplePluginTest {
    @Test void someLibraryMethodReturnsTrue() {
        assertTrue(true, "aoeu");
    }
}
